"use client";

import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { Card, Typography } from "antd";
import styles from "./AnomalyNarrative.module.scss";

const { Paragraph } = Typography;

interface AnomalyNarrativeProps {
  /** Markdown narrative from the backend; absent when the LLM is disabled. */
  analysis?: string;
}

/**
 * Optional LLM narrative for an anomaly.
 *
 * The backend sends `llm_analysis` as markdown (bold lead line, headings and
 * GFM tables), so it is rendered with `react-markdown` + `remark-gfm`.
 * `react-markdown`'s default safe behaviour is kept: raw HTML stays disabled,
 * with no raw-HTML plugin and no unsafe inner-HTML escape hatch, so the model
 * cannot inject markup. The narrative is additive - the deterministic
 * `reason` and `recommended_action` remain the authoritative record.
 */
export function AnomalyNarrative({ analysis }: AnomalyNarrativeProps) {
  const narrative = analysis?.trim() ?? "";

  return (
    <Card>
      <section aria-labelledby="llm-narrative-heading">
        <h2 id="llm-narrative-heading" className={styles.heading}>
          LLM narrative
        </h2>
        <Paragraph type="secondary" className={styles.note}>
          Interpretation generated by the LLM for this anomaly. It is additional
          context and never replaces the deterministic reason, recommended
          action and statistics above.
        </Paragraph>
        {narrative.length === 0 ? (
          <Paragraph className={styles.empty}>
            No LLM narrative is available for this anomaly.
          </Paragraph>
        ) : (
          <div className={styles.narrative}>
            <ReactMarkdown remarkPlugins={[remarkGfm]}>
              {narrative}
            </ReactMarkdown>
          </div>
        )}
      </section>
    </Card>
  );
}
